name: .NET

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Setup paket
      run: dotnet tool install paket
    - name: Install paket
      run: paket install
    - name: Restore dependencies
      run: dotnet restore ./blossom-cli
    - name: Build
      run: dotnet build --no-restore ./blossom-cli
  #  - name: Test
  #    run: dotnet test --no-build --verbosity normal
